<?xml version="1.0" encoding="utf-8"?><Database Name="Clinic" Class="DataClassesClinicDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=(local)\SQLEXPRESS;Initial Catalog=Clinic;Integrated Security=True" SettingsObjectName="DataLayer.Properties.Settings" SettingsPropertyName="ClinicConnectionString1" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Visit" Member="Visits">
    <Type Name="Visit">
      <Column Name="VisitId" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="PatientId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ReceptionistId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="DoctorId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Description" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="Diagnosis" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="Status" Type="System.String" DbType="NVarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="DateOfRegistration" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="EndCancelDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Association Name="Visit_LaboratoryExamination" Member="LaboratoryExaminations" ThisKey="VisitId" OtherKey="VisitId" Type="LaboratoryExamination" />
      <Association Name="Visit_PhysicalExamination" Member="PhysicalExaminations" ThisKey="VisitId" OtherKey="VisitId" Type="PhysicalExamination" />
      <Association Name="Doctor_Visit" Member="Doctor" ThisKey="DoctorId" OtherKey="DoctorId" Type="Doctor" IsForeignKey="true" />
      <Association Name="Patient_Visit" Member="Patient" ThisKey="PatientId" OtherKey="PatientId" Type="Patient" IsForeignKey="true" />
      <Association Name="Receptionist_Visit" Member="Receptionist" ThisKey="ReceptionistId" OtherKey="ReceptionistId" Type="Receptionist" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Address" Member="Addresses">
    <Type Name="Address">
      <Column Name="AddressId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="City" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Street" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="HouseNr" Type="System.String" DbType="NVarChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="PlaceNr" Type="System.String" DbType="NVarChar(10)" CanBeNull="true" />
      <Column Name="ZipCode" Type="System.String" DbType="NVarChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="Province" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Phone" Type="System.String" DbType="NVarChar(12)" CanBeNull="true" />
      <Association Name="Address_Doctor" Member="Doctors" ThisKey="AddressId" OtherKey="AddressId" Type="Doctor" />
      <Association Name="Address_LaboratoryManager" Member="LaboratoryManagers" ThisKey="AddressId" OtherKey="AddressId" Type="LaboratoryManager" />
      <Association Name="Address_LabWorker" Member="LabWorkers" ThisKey="AddressId" OtherKey="AddressId" Type="LabWorker" />
      <Association Name="Address_Patient" Member="Patients" ThisKey="AddressId" OtherKey="AddressId" Type="Patient" />
      <Association Name="Address_Receptionist" Member="Receptionists" ThisKey="AddressId" OtherKey="AddressId" Type="Receptionist" />
    </Type>
  </Table>
  <Table Name="dbo.DictionaryMedicalExamination" Member="DictionaryMedicalExaminations">
    <Type Name="DictionaryMedicalExamination">
      <Column Name="MedicalExaminationCode" Type="System.String" DbType="Char(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Type" Type="System.String" DbType="NChar(3) NOT NULL" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(254)" CanBeNull="true" />
      <Association Name="DictionaryMedicalExamination_LaboratoryExamination" Member="LaboratoryExaminations" ThisKey="MedicalExaminationCode" OtherKey="MedicalExaminationCode" Type="LaboratoryExamination" />
      <Association Name="DictionaryMedicalExamination_PhysicalExamination" Member="PhysicalExaminations" ThisKey="MedicalExaminationCode" OtherKey="MedicalExaminationCode" Type="PhysicalExamination" />
    </Type>
  </Table>
  <Table Name="dbo.Doctor" Member="Doctors">
    <Type Name="Doctor">
      <Column Name="DoctorId" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Uname" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="AddressId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="npwz" Type="System.String" DbType="NVarChar(12) NOT NULL" CanBeNull="false" />
      <Column Name="Specialization" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Association Name="Doctor_Visit" Member="Visits" ThisKey="DoctorId" OtherKey="DoctorId" Type="Visit" />
      <Association Name="Address_Doctor" Member="Address" ThisKey="AddressId" OtherKey="AddressId" Type="Address" IsForeignKey="true" />
      <Association Name="User_Doctor" Member="User" ThisKey="Uname" OtherKey="Uname" Type="User" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.LaboratoryExamination" Member="LaboratoryExaminations">
    <Type Name="LaboratoryExamination">
      <Column Name="LaboratoryExaminationId" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="MedicalExaminationCode" Type="System.String" DbType="Char(10) NOT NULL" CanBeNull="false" />
      <Column Name="VisitId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="LabWorkerId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="LaboratoryManagerId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="DoctorAttention" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="OrderDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="Result" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="EndCancelDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="MenagerAttention" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="ApprovalCancelDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Status" Type="System.String" DbType="NVarChar(20) NOT NULL" CanBeNull="false" />
      <Association Name="DictionaryMedicalExamination_LaboratoryExamination" Member="DictionaryMedicalExamination" ThisKey="MedicalExaminationCode" OtherKey="MedicalExaminationCode" Type="DictionaryMedicalExamination" IsForeignKey="true" />
      <Association Name="Visit_LaboratoryExamination" Member="Visit" ThisKey="VisitId" OtherKey="VisitId" Type="Visit" IsForeignKey="true" />
      <Association Name="LaboratoryManager_LaboratoryExamination" Member="LaboratoryManager" ThisKey="LaboratoryManagerId" OtherKey="LaboratoryManagerId" Type="LaboratoryManager" IsForeignKey="true" />
      <Association Name="LabWorker_LaboratoryExamination" Member="LabWorker" ThisKey="LabWorkerId" OtherKey="LabWorkerId" Type="LabWorker" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.LaboratoryManager" Member="LaboratoryManagers">
    <Type Name="LaboratoryManager">
      <Column Name="LaboratoryManagerId" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Uname" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="AddressId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Specialization" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Association Name="LaboratoryManager_LaboratoryExamination" Member="LaboratoryExaminations" ThisKey="LaboratoryManagerId" OtherKey="LaboratoryManagerId" Type="LaboratoryExamination" />
      <Association Name="Address_LaboratoryManager" Member="Address" ThisKey="AddressId" OtherKey="AddressId" Type="Address" IsForeignKey="true" />
      <Association Name="User_LaboratoryManager" Member="User" ThisKey="Uname" OtherKey="Uname" Type="User" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.LabWorker" Member="LabWorkers">
    <Type Name="LabWorker">
      <Column Name="LabWorkerId" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Uname" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="AddressId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Specialization" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="ManagerId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="LabWorker_LaboratoryExamination" Member="LaboratoryExaminations" ThisKey="LabWorkerId" OtherKey="LabWorkerId" Type="LaboratoryExamination" />
      <Association Name="Address_LabWorker" Member="Address" ThisKey="AddressId" OtherKey="AddressId" Type="Address" IsForeignKey="true" />
      <Association Name="User_LabWorker" Member="User" ThisKey="Uname" OtherKey="Uname" Type="User" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Patient" Member="Patients">
    <Type Name="Patient">
      <Column Name="PatientId" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="AddressId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="FirstName" Type="System.String" DbType="NVarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="LastName" Type="System.String" DbType="NVarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="Pesel" Type="System.String" DbType="NChar(11) NOT NULL" CanBeNull="false" />
      <Column Name="Sex" Type="System.Char" DbType="NChar(1)" CanBeNull="true" />
      <Column Name="BirthdayDate" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="NIP" Type="System.String" DbType="NVarChar(13)" CanBeNull="true" />
      <Column Name="Insurance" Type="System.Char" DbType="NChar(1) NOT NULL" CanBeNull="false" />
      <Association Name="Patient_Visit" Member="Visits" ThisKey="PatientId" OtherKey="PatientId" Type="Visit" />
      <Association Name="Address_Patient" Member="Address" ThisKey="AddressId" OtherKey="AddressId" Type="Address" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.PhysicalExamination" Member="PhysicalExaminations">
    <Type Name="PhysicalExamination">
      <Column Name="PhysicalExaminationId" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="MedicalExaminationCode" Type="System.String" DbType="Char(10) NOT NULL" CanBeNull="false" />
      <Column Name="VisitId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Result" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Association Name="DictionaryMedicalExamination_PhysicalExamination" Member="DictionaryMedicalExamination" ThisKey="MedicalExaminationCode" OtherKey="MedicalExaminationCode" Type="DictionaryMedicalExamination" IsForeignKey="true" />
      <Association Name="Visit_PhysicalExamination" Member="Visit" ThisKey="VisitId" OtherKey="VisitId" Type="Visit" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Receptionist" Member="Receptionists">
    <Type Name="Receptionist">
      <Column Name="ReceptionistId" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Uname" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="AddressId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Email" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Association Name="Receptionist_Visit" Member="Visits" ThisKey="ReceptionistId" OtherKey="ReceptionistId" Type="Visit" />
      <Association Name="Address_Receptionist" Member="Address" ThisKey="AddressId" OtherKey="AddressId" Type="Address" IsForeignKey="true" />
      <Association Name="User_Receptionist" Member="User" ThisKey="Uname" OtherKey="Uname" Type="User" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.[User]" Member="Users">
    <Type Name="User">
      <Column Name="Uname" Type="System.String" DbType="NVarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="FirstName" Type="System.String" DbType="NVarChar(40) NOT NULL" CanBeNull="false" />
      <Column Name="LastName" Type="System.String" DbType="NVarChar(40) NOT NULL" CanBeNull="false" />
      <Column Name="Role" Type="System.String" DbType="NVarChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="DateRetire" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="PersonId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Password" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Association Name="User_Doctor" Member="Doctors" ThisKey="Uname" OtherKey="Uname" Type="Doctor" />
      <Association Name="User_LaboratoryManager" Member="LaboratoryManagers" ThisKey="Uname" OtherKey="Uname" Type="LaboratoryManager" />
      <Association Name="User_LabWorker" Member="LabWorkers" ThisKey="Uname" OtherKey="Uname" Type="LabWorker" />
      <Association Name="User_Receptionist" Member="Receptionists" ThisKey="Uname" OtherKey="Uname" Type="Receptionist" />
    </Type>
  </Table>
</Database>